<a href="https://colab.research.google.com/github/Sujit-Rukade/DSML-Course/blob/main/Colab_notebooks/Feature_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('satandar.csv')
df.shape

(24174, 371)

# Filtering Using the Variance Threshold

In [ ]:
from sklearn.feature_selection import VarianceThreshold
vt = VarianceThreshold(threshold = 1)

In [ ]:
vt.fit(df)

VarianceThreshold(threshold=1)

In [ ]:
newdf = df.iloc[:, vt.get_support()]

In [ ]:
newdf.shape

(24174, 169)

# Dropping Duplicate Values

In [ ]:
df.shape

(22830, 371)

In [ ]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
24169    False
24170    False
24171    False
24172    False
24173    False
Length: 24174, dtype: bool

In [ ]:
df_t = df.T

In [ ]:
df_t

,0,1,2,3,4,5,6,7,8,9,...,24164,24165,24166,24167,24168,24169,24170,24171,24172,24173
ID,1.00,3.00,4.00,8.00,10.000000,13.00,14.00,18.00,20.00,23.00,...,48340.00,48342.00,48344.00,48345.00,48347.000000,48349.00,48350.00,48351.00,48352.00,48353.0
var3,2.00,2.00,2.00,2.00,2.000000,2.00,2.00,2.00,2.00,2.00,...,2.00,2.00,2.00,2.00,2.000000,2.00,2.00,2.00,2.00,2.0
var15,23.00,34.00,23.00,37.00,39.000000,23.00,27.00,26.00,45.00,25.00,...,26.00,51.00,23.00,23.00,46.000000,71.00,23.00,38.00,40.00,23.0
imp_ent_var16_ult1,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.0
imp_op_var39_comer_ult1,0.00,0.00,0.00,195.00,0.000000,0.00,0.00,0.00,0.00,0.00,...,0.00,475.38,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
saldo_medio_var44_hace3,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,NaN
saldo_medio_var44_ult1,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,NaN
saldo_medio_var44_ult3,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,NaN
var38,39205.17,49278.03,67333.77,64007.97,117310.979016,87975.75,94956.66,251638.95,101962.02,356463.06,...,326853.09,86064.84,200462.31,179527.41,117310.979016,122374.41,98297.52,136660.95,71016.51,NaN
TARGET,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.000000,0.00,0.00,0.00,0.00,NaN

In [ ]:
df_t.drop_duplicates(inplace = True)

In [ ]:
df = df_t.T

In [ ]:
df.shape

(24174, 288)